/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyanogenmod_asusdec_AsusdecNative */

#ifndef _Included_com_cyanogenmod_asusdec_AsusdecNative
#define _Included_com_cyanogenmod_asusdec_AsusdecNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyanogenmod_asusdec_AsusdecNative
 * Method:    toggleTouchpad
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cyanogenmod_asusdec_AsusdecNative_toggleTouchpad
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
